// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nobqpuvkujlljghbjyqp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5vYnFwdXZrdWpsbGpnaGJqeXFwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDcxNDI1NzYsImV4cCI6MjA2MjcxODU3Nn0.ZCHWSY93AfNNEHvXFidPU1OkBEXJKBNtl6KWunILhdg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);